// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package app

// Injectors from wire.go:

func NewApplication() (*Application, error) {
	test := Test{}
	application := &Application{
		Test: test,
	}
	return application, nil
}
